from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from backend import services
from analysis.exports import holdings_llm_text, recommendation_llm_text, watchlist_llm_text
from storage.json_store import write_report


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def build_report(app_state: dict) -> str:
    recommendation = app_state["recommendation"]
    holdings = app_state["holdings"]
    settings = app_state["settings"]
    picks = app_state["weeklyPicks"][:10]
    watchlist = app_state["watchlistAnalysis"]

    lines = [
        f"# Weekly TFSA Research Report - {date.today().isoformat()}",
        "",
        "This report is generated by rule-based analysis using local/mock data unless optional providers are configured.",
        "",
        "## Recommendation Summary",
        "",
        recommendation.get("summary", "No recommendation summary."),
        "",
    ]
    if recommendation.get("mainRecommendations"):
        lines.extend([
            markdown_table(
                ["Rank", "Ticker", "Action", "Score", "Amount", "Shares", "Warning"],
                [
                    [
                        row["rank"],
                        row["ticker"],
                        row["actionLabel"],
                        row["finalScore"],
                        f"{row['suggestedCurrency']} {row['suggestedAmount']}",
                        row["estimatedShares"],
                        row["portfolioWarningStatus"],
                    ]
                    for row in recommendation["mainRecommendations"]
                ],
            ),
            "",
        ])
    if recommendation.get("portfolioWarnings"):
        lines.extend(["## Portfolio Warnings", ""])
        for warning in recommendation["portfolioWarnings"]:
            lines.append(f"- {warning['warningMessage']}")
        lines.append("")
    if recommendation.get("planB"):
        lines.extend(["## Plan B Allocation", ""])
        for row in recommendation["planB"]:
            lines.append(f"- {row['ticker']}: {settings.get('investmentCurrency', 'CAD')} {row['suggestedAmount']}")
        lines.append("")

    lines.extend([
        "## Weekly Picks",
        "",
        markdown_table(
            ["Ticker", "Type", "Theme", "Score", "Risk", "Suggested action"],
            [[row["ticker"], row["type"], row["theme"], row["score"], row["riskLevel"], row["suggestedAction"]] for row in picks],
        ),
        "",
        "## Watchlist Snapshot",
        "",
        markdown_table(
            ["Ticker", "Type", "Score", "Action", "Risk", "Price"],
            [[row["ticker"], row["type"], row["finalScore"], row["actionLabel"], row["riskLevel"], f"{row.get('currency')} {row.get('latestClose')}"] for row in watchlist],
        ),
        "",
        "## Holdings Snapshot",
        "",
        markdown_table(
            ["Ticker", "Shares", "Avg Cost", "Market Value CAD", "Weight", "Action"],
            [
                [
                    row["ticker"],
                    row["shares"],
                    f"{row['currency']} {row['averageCost']}",
                    row["currentMarketValueCad"],
                    f"{row['portfolioWeight']}%",
                    row["currentActionLabel"],
                ]
                for row in holdings
            ],
        ),
        "",
        "## LLM Export Blocks",
        "",
        "### Recommendation",
        "",
        "```text",
        recommendation_llm_text(recommendation, holdings, settings),
        "```",
        "",
        "### Watchlist",
        "",
        "```text",
        watchlist_llm_text(watchlist, settings),
        "```",
        "",
        "### Holdings",
        "",
        "```text",
        holdings_llm_text(holdings, settings),
        "```",
    ])
    return "\n".join(lines)


def main() -> None:
    app_state = services.state()
    report_name = f"{date.today().isoformat()}-weekly-report.md"
    write_report(report_name, build_report(app_state))
    print(f"Generated {report_name}")
    print(f"Main recommendations: {len(app_state['recommendation'].get('mainRecommendations', []))}")
    print(f"Weekly picks: {len(app_state['weeklyPicks'])}")
    print(f"Holdings: {len(app_state['holdings'])}")


if __name__ == "__main__":
    main()
