from __future__ import annotations

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from backend import services


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> None:
    app_state = services.state()
    assert_true(len(app_state["watchlistAnalysis"]) >= 1, "watchlist analysis should not be empty")
    assert_true(len(app_state["weeklyPicks"]) >= 1, "weekly picks should not be empty")
    assert_true("mainRecommendations" in app_state["recommendation"], "recommendation payload missing mainRecommendations")
    assert_true("portfolioWarnings" in app_state["recommendation"], "recommendation payload missing warnings")
    assert_true("holdingContext" in app_state["recommendation"], "recommendation payload missing holding context")
    assert_true("planB" in app_state["recommendation"], "recommendation payload missing Plan B")
    assert_true(len(app_state["holdings"]) >= 1, "holdings should be calculated from transactions")
    rec = services.calculate_with_overrides({"investmentAmount": 1000, "investmentCurrency": "CAD"})
    assert_true("summary" in rec, "calculated recommendation should include summary")
    assert_true(len(rec["portfolioWarnings"]) == 0, "target allocation warnings should be hidden by default")
    assert_true(len(rec["planB"]) == 0, "Plan B should not be generated by default")
    skipped = services.calculate_with_overrides({"investmentAmount": 1000, "investmentCurrency": "CAD", "skippedTickers": [rec["mainRecommendations"][0]["ticker"]]})
    assert_true(len(skipped["planB"]) >= 1, "Plan B should be generated when a ticker is manually skipped")
    print("Smoke test passed.")
    print(f"Watchlist rows: {len(app_state['watchlistAnalysis'])}")
    print(f"Holdings: {len(app_state['holdings'])}")
    print(f"Recommendations: {len(rec['mainRecommendations'])}")
    print(f"Warnings: {len(rec['portfolioWarnings'])}")
    print(f"Plan B rows: {len(rec['planB'])}")


if __name__ == "__main__":
    main()
